### ISSUE TITLE
IsXml.Equals() indicates a match when it shouldn't in some cases

### ISSUE THREAD

**Issue by bespey-bkfs** [netbike/netbike.xmlunit#1]
This expected XML:

```
<root><ns1:a xmlns:ns1='bespey.test'>hello world</ns1:a></root>
```

evaluates to an IsXml match when compared against this XML:

```
<root><ns1:a xmlns:ns1='bespey.test'><b att1='val1'><c>hello world</c></b></ns1:a></root>
```

i.e. this NUnit assertion passes, even though it shouldn't:

```
Assert.That(xml, IsXml.Equals(EXPECTED_XML).WithIgnore(XmlComparisonType.NamespacePrefix).WithNormalizeText());
```

The second XML has nested elements under the ns1:a node, so it should not match the ns1:a node in the expected XML

**Comment by a7b0** [comment]
a long time ago.. thanks for your issue!
